### PR TITLE
feat(auth): add login and register pages

### LINKED ISSUE #4: Đăng nhập
Image

- [x] Tạo form đăng nhập gồm identify (tên đăng nhập hoặc email hoặc số điện thoại) và password (mật khẩu)
- [x] Get started dẫn về trang Đăng ký
- [x] Forgot password dẫn về trang Quên mật khẩu
- [x] Nút Đăng nhập
- [ ] Đăng nhập bằng mạng xã hội: Google và Facebook => về trang chủ
- [ ] Sau khi gọi API báo lỗi nếu identify hoặc password sai

### PR DESCRIPTION
**Pull request by truongcongtrung2709**
Vì chưa có back-end và api nên chưa login bằng google, facebook và identify

### CODE REVIEW

**Comment by zendy199x** [comment]
For each component's interface props, you should clearly set its name, for easy searching and debugging.

**Comment by zendy199x** [comment]
@truongcongtrung2709  In NextJS, if it is an image with jpg extension,... if possible, you should convert it to webp to optimize SEO.

**Comment by zendy199x** [comment]
@truongcongtrung2709  Any component that is not imported using useState, etc. is not a client side component. You should not use 'use-client' because then it will turn your component into a client side component, although you can leave it in NextJS. understand it as server side component

**Comment by zintaen** [comment]
@truongcongtrung2709 @zendy199x I've added forgot password page and refactor to fit with our code convention, merged into develop branch

**Pull request merged**
